name: Publish Docs

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build DocC
        run: |
          swift package --allow-writing-to-directory ./docs generate-documentation \
          --target LiveKit \
          --output-path ./docs \
          --transform-for-static-hosting \
          --hosting-base-path client-sdk-swift/

      - name: S3 Upload
        run: aws s3 cp docs/ s3://livekit-docs/client-sdk-swift --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DOCS_DEPLOY_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCS_DEPLOY_AWS_API_SECRET }}
          AWS_DEFAULT_REGION: "us-east-1"

      - name: Invalidate cache
        run: aws cloudfront create-invalidation --distribution-id EJJ40KLJ3TRY9 --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DOCS_DEPLOY_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCS_DEPLOY_AWS_API_SECRET }}
          AWS_DEFAULT_REGION: "us-east-1"
